# Generated by Django 4.0 on 2022-07-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default='DEFAULT VALUE', max_length=140),
        ),
    ]
