# Generated by Django 4.0 on 2022-07-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
